### ISSUE TITLE
Some questions after reading the paper

### ISSUE THREAD

**Issue by Logan507** [nikita-0209/downsample-sst#2]
Hi, Thanks for sharing your paper and codes.I have some questions after reading your paper:
1. Are the training datasets used in the code all within a specific area(Bay of Bengal), or are they global SST?
2. Are the resolution of 5km and 25km in the paper degenerated from 1km by using bicubic interpolation?
Finally, could you share the .h5 file used in the code? My E-mail address is loganyang9439@gmail.com.
Thank you very much.

Best regards,
Logan

**Comment by nikita-0209** [comment]
Hi Logan

1. Yep, all the datasets are of Bay of Bengal.
2. No, these datasets were generated by using average smoothing on the 1km dataset.

Sure, would you like the h5 files for all three resolutions - 1km, 5km, and 25km?

**Comment by Logan507** [comment]
Thank you for your answer, can you send me all three resolutions - 1km, 5km, and 25km?
My mail address is loganyang9439@gmail.com.

**Comment by nikita-0209** [comment]
Hi, I've shared the files with you.

**Comment by ChengqingZhang** [comment]
Hi, Thanks for sharing your paper and codes.I have some questions after reading your paper:could you share the  file used in the code? My E-mail address is (22234158@zju.edu.cn).

**Comment by nikita-0209** [comment]
hi, done :)

**Comment by ChengqingZhang** [comment]
Hi, Thanks for sharing your files.I have some questions after running your codes.Why the shape of the file 'st8km_ Com.nc' and 'st24km_  com.nc' is different.'st8km_ Com.nc' （240，75，150），'st24km_ Com.nc' (240, 25, 50)？thanks

**Comment by zafor44** [comment]
Could you please share your file with me.my email address is zaforku@gmail.com 
Thanks and regards
